version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://mosquitto:1883